variables:
  BUILD_SCRIPTS_PATH: '$CI_PROJECT_DIR/BuildScripts'

stages:
  - package

Keyboard::package:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  script:
    # Run the GeneratePackage script
    - cd $CI_PROJECT_DIR
    - "& ./BuildScripts/GeneratePackage.bat"
  artifacts:
    name: "CapableKeyboard_$CI_COMMIT_SHORT_SHA"
    paths:
      - $CI_PROJECT_DIR/CapableKeyboard.unitypackage
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10
