variables:
  BUILD_SCRIPTS_PATH: '$CI_PROJECT_DIR/BuildScripts'

stages:
  - package

Keyboard::package:
  stage: package
  when: always
  script:
    # Run the GeneratePackage script
    - cd $CI_PROJECT_DIR
    - "& ./BuildScripts/GeneratePackage.bat"
  artifacts:
    name: "CapableKeyboard_${env:CI_COMMIT_SHA}"
    paths:
      - ${env:BUILD_SCRIPTS_PATH}/CapableKeyboard.unitypackage
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10
